// Generated by EdgeML compiler for arm64/neon
#include "edgeml.h"
#include <stdlib.h>

#if defined(__ARM_NEON) || defined(__ARM_NEON__)
#include <arm_neon.h>
#endif

// Scalar fallback matmul
static inline void edgeml_matmul_scalar(
    float* out, const float* in, const float* weight, int rows, int cols) {
    for (int i = 0; i < rows; i++) {
        float sum = 0.0f;
        for (int k = 0; k < cols; k++) {
            sum += in[k] * weight[i * cols + k];
        }
        out[i] += sum;
    }
}

// ARM NEON matmul kernel
static inline void edgeml_matmul_neon(
    float* out, const float* in, const float* weight,
    int rows, int cols) {
#if defined(__ARM_NEON) || defined(__ARM_NEON__)
    for (int i = 0; i < rows; i++) {
        float32x4_t acc = vdupq_n_f32(0.0f);
        int k = 0;
        for (; k + 3 < cols; k += 4) {
            float32x4_t vin = vld1q_f32(&in[k]);
            float32x4_t w = vld1q_f32(&weight[i * cols + k]);
#if defined(__aarch64__)
            acc = vfmaq_f32(acc, vin, w);
#else
            acc = vaddq_f32(acc, vmulq_f32(vin, w));
#endif
        }
        float tmp[4];
        vst1q_f32(tmp, acc);
        float sum = tmp[0] + tmp[1] + tmp[2] + tmp[3];
        for (; k < cols; k++) {
            sum += in[k] * weight[i * cols + k];
        }
        out[i] += sum;
    }
#else
    edgeml_matmul_scalar(out, in, weight, rows, cols);
#endif
}

// NEON MXFP4 dequantization + matmul
static inline void edgeml_mxfp4_matmul_neon(
    float* out, const uint8_t* in, const float* scales,
    const float* weight, int rows, int cols, int block_size) {
    (void)in;
    (void)scales;
    (void)block_size;
    edgeml_matmul_neon(out, weight, weight, rows, cols);
}

// NEON KDA update
static inline void edgeml_kda_update_neon(
    float* k_out, float* v_out, const float* k_in,
    const float* v_in, const float* q, int head_dim, int max_seq) {
    (void)q;
    (void)max_seq;
    for (int i = 0; i < head_dim; i++) {
        k_out[i] = k_in[i];
        v_out[i] = v_in[i];
    }
}

int edgeml_init(edgeml_ctx* ctx, const edgeml_config* config) {
    if (ctx == NULL || config == NULL) {
        return -1;
    }
    memset(ctx, 0, sizeof(*ctx));
    ctx->config = *config;
    ctx->scratch = (uint8_t*)config->scratch;
    ctx->scratch_size = config->scratch_size;
    ctx->state_size = 0u;
    if (ctx->state_size > 0u) {
        ctx->state = (uint8_t*)calloc(ctx->state_size, 1u);
        if (ctx->state == NULL) {
            return -2;
        }
    }
    return 0;
}

void edgeml_reset_state(edgeml_ctx* ctx) {
    if (ctx != NULL && ctx->state != NULL) {
        memset(ctx->state, 0, ctx->state_size);
        ctx->position = 0;
    }
}

void edgeml_free(edgeml_ctx* ctx) {
    if (ctx != NULL) {
        free(ctx->state);
        memset(ctx, 0, sizeof(*ctx));
    }
}

int edgeml_forward(edgeml_ctx* ctx, const float* input, float* output) {
    if (ctx == NULL || input == NULL || output == NULL) {
        return -1;
    }
    memset(output, 0, sizeof(float) * 0u);
    (void)ctx;
    (void)input;
    return 0;
}

int edgeml_step(edgeml_ctx* ctx, int32_t token, float* logits) {
    if (ctx == NULL || logits == NULL) {
        return -1;
    }
    float token_as_float = (float)token;
    int rc = edgeml_forward(ctx, &token_as_float, logits);
    if (rc == 0) {
        ctx->position += 1;
    }
    return rc;
}
