#ifndef EDGEML_H
#define EDGEML_H

#include <stdint.h>
#include <stddef.h>
#include <string.h>

// Generated by EdgeML compiler for arm64/neon

// Configuration struct
typedef struct {
    float* embed_w;  // weight: 1048576 bytes
    float* fc1_w;  // weight: 524288 bytes
    float* fc2_w;  // weight: 524288 bytes
    void* scratch;
    size_t scratch_size;
} edgeml_config;

// Runtime context
typedef struct {
    edgeml_config config;
    uint8_t* state;
    size_t state_size;
    uint8_t* scratch;
    size_t scratch_size;
    int32_t position;
} edgeml_ctx;

// Function declarations
int edgeml_init(edgeml_ctx* ctx, const edgeml_config* config);
int edgeml_forward(edgeml_ctx* ctx, const float* input, float* output);
int edgeml_step(edgeml_ctx* ctx, int32_t token, float* logits);
void edgeml_reset_state(edgeml_ctx* ctx);
void edgeml_free(edgeml_ctx* ctx);

#endif // EDGEML_H