/**
 * esbuild production bundle — one hashed chunk graph per route entry.
 *
 * Usage (from repo root):
 *   cd web && npm install && npm run build
 *
 * Output: web/dist/* + web/dist/manifest.json + web/dist/boot.js
 * Production hosts load ./dist/boot.js via index.html boot loader.
 */

import * as esbuild from "esbuild";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { basename, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const OUT = join(ROOT, "dist");
const DEV_ONLY_RE = /\/\* DEV-ONLY-START \*\/[\s\S]*?\/\* DEV-ONLY-END \*\//g;

/** Strip dev-only blocks when building the production bundle. */
function stripDevOnlyPlugin(enabled) {
  return {
    name: "strip-dev-only",
    setup(build) {
      if (!enabled) return;
      build.onLoad({ filter: /\.(js|mjs)$/ }, async (args) => {
        if (!args.path.startsWith(ROOT)) return null;
        const contents = await readFile(args.path, "utf8");
        if (!contents.includes("DEV-ONLY-START")) return null;
        return {
          contents: contents.replace(DEV_ONLY_RE, ""),
          loader: args.path.endsWith(".mjs") ? "js" : "js",
        };
      });
    },
  };
}

const ENTRIES = {
  app: join(ROOT, "app.js"),
  theme: join(ROOT, "theme.js"),
  splash: join(ROOT, "splash.js"),
  "favicon-bounce": join(ROOT, "favicon-bounce.js"),
  "prep-disputes-boot": join(ROOT, "prep-disputes-boot.mjs"),
};

/** Load order for production boot.js (side-effect entries before app). */
const BOOT_ORDER = ["favicon-bounce", "theme", "splash", "prep-disputes-boot", "app"];

/** @param {string} outPath */
function relDist(outPath) {
  const norm = outPath.replace(/\\/g, "/");
  const marker = "/dist/";
  const idx = norm.lastIndexOf(marker);
  if (idx >= 0) return `./${norm.slice(idx + marker.length)}`;
  return `./${basename(norm)}`;
}

function fmtBytes(n) {
  if (n >= 1024 * 1024) return `${(n / (1024 * 1024)).toFixed(1)} MB`;
  if (n >= 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${n} B`;
}

/** @param {string} entryPoint */
function entryKey(entryPoint) {
  const ep = entryPoint.replace(/\\/g, "/");
  const epBase = basename(ep);
  for (const [key, entryPath] of Object.entries(ENTRIES)) {
    const base = basename(entryPath.replace(/\\/g, "/"));
    if (ep === base || ep.endsWith(`/${base}`)) return key;
  }
  return null;
}

await mkdir(OUT, { recursive: true });

const productionBuild = process.env.PRODUCTION_BUILD === "1";

const result = await esbuild.build({
  entryPoints: ENTRIES,
  bundle: true,
  splitting: true,
  format: "esm",
  outdir: OUT,
  entryNames: "[name]-[hash]",
  chunkNames: "chunks/[name]-[hash]",
  assetNames: "assets/[name]-[hash]",
  metafile: true,
  sourcemap: true,
  target: ["es2020"],
  legalComments: "none",
  logLevel: "info",
  define: { __PROD_BUNDLE__: productionBuild ? "true" : "false" },
  plugins: [stripDevOnlyPlugin(productionBuild)],
});

/** @type {Record<string, string>} */
const manifest = {};

for (const [outPath, meta] of Object.entries(result.metafile.outputs)) {
  if (!meta.entryPoint) continue;
  const key = entryKey(meta.entryPoint);
  if (key) manifest[key] = relDist(outPath);
}

for (const key of Object.keys(ENTRIES)) {
  if (!manifest[key]) {
    throw new Error(`Build missing manifest entry for ${key}`);
  }
}

await writeFile(join(OUT, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);

const boot = `// Generated by web/scripts/build.mjs — do not edit
const manifest = ${JSON.stringify(manifest, null, 2)};
const bootOrder = ${JSON.stringify(BOOT_ORDER)};
for (const key of bootOrder) {
  const href = manifest[key];
  if (href) await import(new URL(href, import.meta.url).href);
}
`;

await writeFile(join(OUT, "boot.js"), boot);

let totalBytes = 0;
let jsBytes = 0;
let mapBytes = 0;
const entryRows = [];

for (const [outPath, meta] of Object.entries(result.metafile.outputs)) {
  totalBytes += meta.bytes;
  const name = relDist(outPath);
  if (name.endsWith(".map")) {
    mapBytes += meta.bytes;
    continue;
  }
  if (name.endsWith(".js")) jsBytes += meta.bytes;
  if (meta.entryPoint) {
    const key = entryKey(meta.entryPoint);
    if (key && key in ENTRIES) {
      entryRows.push({ key, name, bytes: meta.bytes });
    }
  }
}

entryRows.sort((a, b) => BOOT_ORDER.indexOf(a.key) - BOOT_ORDER.indexOf(b.key));

console.log("\nBuild complete — manifest:");
console.log(manifest);
console.log("\nEntry bundles:");
for (const row of entryRows) {
  console.log(`  ${row.key.padEnd(20)} ${fmtBytes(row.bytes).padStart(8)}  ${row.name}`);
}
console.log(
  `\nOutput: ${Object.keys(result.metafile.outputs).length} files, ` +
    `${fmtBytes(jsBytes)} JS (${fmtBytes(mapBytes)} maps), ${fmtBytes(totalBytes)} total`,
);
console.log("\nProduction: portal hostnames load ./dist/boot.js via index.html");
console.log("Local prod test: http://127.0.0.1:8788/?bundle=1 (after npm run build)");
