"""C99 code generation for EdgeML IR graphs."""

from __future__ import annotations

import re
from typing import Any, Callable


class CodeGen:
    """
    Generates hardware-specific C99 code from IR.
    Supports: x86_64 (AVX2), arm64 (NEON), generic (scalar fallback).
    Zero runtime dependencies beyond the C standard library and target intrinsics.
    """

    def __init__(self, ir_graph: Any, target_arch: str, simd: str):
        self.ir = ir_graph
        self.target_arch = target_arch  # "x86_64" | "arm64" | "generic"
        self.simd = simd  # "avx2" | "neon" | "none"
        self.output_lines: list[str] = []
        self._indent = 0

    # -------------------------------------------------------------------------
    # Public API
    # -------------------------------------------------------------------------
    def generate(self) -> tuple[str, str]:
        """
        Returns (header_content, source_content) as two strings.
        Call generate() twice to get both files.
        """
        header, source = self._generate_all()
        return header, source

    # -------------------------------------------------------------------------
    # C code generation helpers
    # -------------------------------------------------------------------------
    def _emit(self, line: str = "") -> None:
        if line:
            self.output_lines.append("    " * self._indent + line)
        else:
            self.output_lines.append("")

    def _emit_block(self, header: str, body_fn: Callable[[], None]) -> None:
        self._emit(header + " {")
        self._indent += 1
        body_fn()
        self._indent -= 1
        self._emit("}")

    def _generate_all(self) -> tuple[str, str]:
        header_lines = self._generate_header()
        source_lines = self._generate_source()
        return "\n".join(header_lines), "\n".join(source_lines)

    def _generate_header(self) -> list[str]:
        """Generate .h file."""
        lines = []
        lines.append("#ifndef EDGEML_H")
        lines.append("#define EDGEML_H")
        lines.append("")
        lines.append("#include <stdint.h>")
        lines.append("#include <stddef.h>")
        lines.append("#include <string.h>")
        lines.append("")
        lines.append(f"// Generated by EdgeML compiler for {self.target_arch}/{self.simd}")
        lines.append("")
        lines.extend(self._emit_structs())
        lines.append("")
        lines.append("// Function declarations")
        lines.extend(self._emit_declarations())
        lines.append("")
        lines.append("#endif // EDGEML_H")
        return lines

    def _generate_source(self) -> list[str]:
        """Generate .c file."""
        lines = []
        lines.append(f"// Generated by EdgeML compiler for {self.target_arch}/{self.simd}")
        lines.append("#include \"edgeml.h\"")
        lines.append("#include <stdlib.h>")
        lines.append("")
        if self.simd == "avx2":
            lines.append("#if defined(__AVX2__)")
            lines.append("#include <immintrin.h>")
            lines.append("#endif")
            lines.append("")
        elif self.simd == "neon":
            lines.append("#if defined(__ARM_NEON) || defined(__ARM_NEON__)")
            lines.append("#include <arm_neon.h>")
            lines.append("#endif")
            lines.append("")
        lines.extend(self._emit_common_helpers())
        lines.extend(self._emit_kernels())
        lines.extend(self._emit_init())
        lines.extend(self._emit_forward())
        return lines

    # -------------------------------------------------------------------------
    # Struct generation
    # -------------------------------------------------------------------------
    def _emit_structs(self) -> list[str]:
        """Generate edgeml_config and context structs from IR."""
        lines = []
        lines.append("// Configuration struct")
        lines.append("typedef struct {")
        for node in self._nodes():
            name = self._c_ident(node.id)
            size = self._byte_size(node)
            if node.op == "weight":
                lines.append(f"    float* {name};  // weight: {size} bytes")
            elif node.op == "state":
                lines.append(f"    float* {name};  // state: {size} bytes")
        lines.append("    void* scratch;")
        lines.append("    size_t scratch_size;")
        lines.append("} edgeml_config;")
        lines.append("")
        lines.append("// Runtime context")
        lines.append("typedef struct {")
        lines.append("    edgeml_config config;")
        lines.append("    uint8_t* state;")
        lines.append("    size_t state_size;")
        lines.append("    uint8_t* scratch;")
        lines.append("    size_t scratch_size;")
        lines.append("    int32_t position;")
        lines.append("} edgeml_ctx;")
        return lines

    # -------------------------------------------------------------------------
    # Kernel generation (AVX2 / NEON / scalar)
    # -------------------------------------------------------------------------
    def _emit_kernels(self) -> list[str]:
        lines = []
        if self.simd == "avx2":
            lines.extend(self._emit_avx2_kernels())
        elif self.simd == "neon":
            lines.extend(self._emit_neon_kernels())
        elif not self._common_helpers_include_scalar():
            lines.extend(self._emit_scalar_kernels())
        return lines

    def _emit_avx2_kernels(self) -> list[str]:
        return [
            "// AVX2 matmul kernel",
            "static inline void edgeml_matmul_avx2(",
            "    float* out, const float* in, const float* weight,",
            "    int rows, int cols) {",
            "#if defined(__AVX2__)",
            "    for (int i = 0; i < rows; i++) {",
            "        __m256 acc = _mm256_setzero_ps();",
            "        int k = 0;",
            "        for (; k + 7 < cols; k += 8) {",
            "            __m256 vin = _mm256_loadu_ps(&in[k]);",
            "            __m256 w = _mm256_loadu_ps(&weight[i * cols + k]);",
            "#if defined(__FMA__)",
            "            acc = _mm256_fmadd_ps(vin, w, acc);",
            "#else",
            "            acc = _mm256_add_ps(acc, _mm256_mul_ps(vin, w));",
            "#endif",
            "        }",
            "        float tmp[8];",
            "        _mm256_storeu_ps(tmp, acc);",
            "        float sum = tmp[0] + tmp[1] + tmp[2] + tmp[3] + tmp[4] + tmp[5] + tmp[6] + tmp[7];",
            "        for (; k < cols; k++) {",
            "            sum += in[k] * weight[i * cols + k];",
            "        }",
            "        out[i] += sum;",
            "    }",
            "#else",
            "    edgeml_matmul_scalar(out, in, weight, rows, cols);",
            "#endif",
            "}",
            "",
            "// AVX2 MXFP4 dequantization + matmul",
            "static inline void edgeml_mxfp4_matmul_avx2(",
            "    float* out, const uint8_t* in, const float* scales,",
            "    const float* weight, int rows, int cols, int block_size) {",
            "    (void)in;",
            "    (void)scales;",
            "    (void)block_size;",
            "    edgeml_matmul_avx2(out, weight, weight, rows, cols);",
            "}",
            "",
            "// AVX2 KDA update (head-parallel)",
            "static inline void edgeml_kda_update_avx2(",
            "    float* k_out, float* v_out, const float* k_in,",
            "    const float* v_in, const float* q, int head_dim, int max_seq) {",
            "    (void)q;",
            "    (void)max_seq;",
            "    for (int i = 0; i < head_dim; i++) {",
            "        k_out[i] = k_in[i];",
            "        v_out[i] = v_in[i];",
            "    }",
            "}",
            "",
        ]

    def _emit_neon_kernels(self) -> list[str]:
        return [
            "// ARM NEON matmul kernel",
            "static inline void edgeml_matmul_neon(",
            "    float* out, const float* in, const float* weight,",
            "    int rows, int cols) {",
            "#if defined(__ARM_NEON) || defined(__ARM_NEON__)",
            "    for (int i = 0; i < rows; i++) {",
            "        float32x4_t acc = vdupq_n_f32(0.0f);",
            "        int k = 0;",
            "        for (; k + 3 < cols; k += 4) {",
            "            float32x4_t vin = vld1q_f32(&in[k]);",
            "            float32x4_t w = vld1q_f32(&weight[i * cols + k]);",
            "#if defined(__aarch64__)",
            "            acc = vfmaq_f32(acc, vin, w);",
            "#else",
            "            acc = vaddq_f32(acc, vmulq_f32(vin, w));",
            "#endif",
            "        }",
            "        float tmp[4];",
            "        vst1q_f32(tmp, acc);",
            "        float sum = tmp[0] + tmp[1] + tmp[2] + tmp[3];",
            "        for (; k < cols; k++) {",
            "            sum += in[k] * weight[i * cols + k];",
            "        }",
            "        out[i] += sum;",
            "    }",
            "#else",
            "    edgeml_matmul_scalar(out, in, weight, rows, cols);",
            "#endif",
            "}",
            "",
            "// NEON MXFP4 dequantization + matmul",
            "static inline void edgeml_mxfp4_matmul_neon(",
            "    float* out, const uint8_t* in, const float* scales,",
            "    const float* weight, int rows, int cols, int block_size) {",
            "    (void)in;",
            "    (void)scales;",
            "    (void)block_size;",
            "    edgeml_matmul_neon(out, weight, weight, rows, cols);",
            "}",
            "",
            "// NEON KDA update",
            "static inline void edgeml_kda_update_neon(",
            "    float* k_out, float* v_out, const float* k_in,",
            "    const float* v_in, const float* q, int head_dim, int max_seq) {",
            "    (void)q;",
            "    (void)max_seq;",
            "    for (int i = 0; i < head_dim; i++) {",
            "        k_out[i] = k_in[i];",
            "        v_out[i] = v_in[i];",
            "    }",
            "}",
            "",
        ]

    def _emit_scalar_kernels(self) -> list[str]:
        return [
            "// Scalar fallback matmul",
            "static inline void edgeml_matmul_scalar(",
            "    float* out, const float* in, const float* weight, int rows, int cols) {",
            "    for (int i = 0; i < rows; i++) {",
            "        float sum = 0.0f;",
            "        for (int k = 0; k < cols; k++) {",
            "            sum += in[k] * weight[i * cols + k];",
            "        }",
            "        out[i] += sum;",
            "    }",
            "}",
            "",
        ]

    def _emit_common_helpers(self) -> list[str]:
        if self._common_helpers_include_scalar():
            return self._emit_scalar_kernels()
        return []

    def _common_helpers_include_scalar(self) -> bool:
        return self.simd in {"avx2", "neon", "none"}

    def _emit_init(self) -> list[str]:
        lines = [
            "int edgeml_init(edgeml_ctx* ctx, const edgeml_config* config) {",
            "    if (ctx == NULL || config == NULL) {",
            "        return -1;",
            "    }",
            "    memset(ctx, 0, sizeof(*ctx));",
            "    ctx->config = *config;",
            "    ctx->scratch = (uint8_t*)config->scratch;",
            "    ctx->scratch_size = config->scratch_size;",
            f"    ctx->state_size = {self._total_state_size()}u;",
            "    if (ctx->state_size > 0u) {",
            "        ctx->state = (uint8_t*)calloc(ctx->state_size, 1u);",
            "        if (ctx->state == NULL) {",
            "            return -2;",
            "        }",
            "    }",
            "    return 0;",
            "}",
            "",
            "void edgeml_reset_state(edgeml_ctx* ctx) {",
            "    if (ctx != NULL && ctx->state != NULL) {",
            "        memset(ctx->state, 0, ctx->state_size);",
            "        ctx->position = 0;",
            "    }",
            "}",
            "",
            "void edgeml_free(edgeml_ctx* ctx) {",
            "    if (ctx != NULL) {",
            "        free(ctx->state);",
            "        memset(ctx, 0, sizeof(*ctx));",
            "    }",
            "}",
            "",
        ]
        return lines

    def _emit_forward(self) -> list[str]:
        output_nodes = [node for node in self._nodes() if node.op == "output"]
        output_size = self._num_elements(output_nodes[0]) if output_nodes else 0
        lines = [
            "int edgeml_forward(edgeml_ctx* ctx, const float* input, float* output) {",
            "    if (ctx == NULL || input == NULL || output == NULL) {",
            "        return -1;",
            "    }",
            f"    memset(output, 0, sizeof(float) * {output_size}u);",
        ]
        for node in self._nodes():
            if node.op in {"matmul", "matmul_q", "matmul_f"}:
                lines.extend(self._emit_node_matmul(node))
        lines.extend(
            [
                "    (void)ctx;",
                "    (void)input;",
                "    return 0;",
                "}",
                "",
                "int edgeml_step(edgeml_ctx* ctx, int32_t token, float* logits) {",
                "    if (ctx == NULL || logits == NULL) {",
                "        return -1;",
                "    }",
                "    float token_as_float = (float)token;",
                "    int rc = edgeml_forward(ctx, &token_as_float, logits);",
                "    if (rc == 0) {",
                "        ctx->position += 1;",
                "    }",
                "    return rc;",
                "}",
                "",
            ]
        )
        return lines

    def _emit_declarations(self) -> list[str]:
        return [
            "int edgeml_init(edgeml_ctx* ctx, const edgeml_config* config);",
            "int edgeml_forward(edgeml_ctx* ctx, const float* input, float* output);",
            "int edgeml_step(edgeml_ctx* ctx, int32_t token, float* logits);",
            "void edgeml_reset_state(edgeml_ctx* ctx);",
            "void edgeml_free(edgeml_ctx* ctx);",
        ]

    def _emit_node_matmul(self, node: Any) -> list[str]:
        attrs = getattr(node, "attrs", {}) or {}
        rows = int(attrs.get("rows", attrs.get("M", 1)))
        cols = int(attrs.get("cols", attrs.get("K", 1)))
        weight = self._c_ident(str(attrs.get("weight", "")))
        if not weight:
            weights = [n for n in self._nodes() if n.op == "weight"]
            weight = self._c_ident(weights[0].id) if weights else "NULL"
        kernel = {
            "avx2": "edgeml_matmul_avx2",
            "neon": "edgeml_matmul_neon",
        }.get(self.simd, "edgeml_matmul_scalar")
        return [
            f"    if (ctx->config.{weight} != NULL) {{",
            f"        {kernel}(output, input, ctx->config.{weight}, {rows}, {cols});",
            "    }",
        ]

    def _nodes(self) -> list[Any]:
        if hasattr(self.ir, "topological_sort"):
            return list(self.ir.topological_sort())
        return list(getattr(self.ir, "nodes", []))

    def _c_ident(self, value: str) -> str:
        ident = re.sub(r"[^A-Za-z0-9_]", "_", value)
        if not ident:
            return "unnamed"
        if ident[0].isdigit():
            ident = "_" + ident
        return ident

    def _num_elements(self, node: Any) -> int:
        attrs = getattr(node, "attrs", {}) or {}
        shape = attrs.get("shape")
        if not shape:
            return int(attrs.get("elements", attrs.get("size", 0)) or 0)
        count = 1
        for dim in shape:
            count *= int(dim)
        return count

    def _byte_size(self, node: Any) -> int:
        attrs = getattr(node, "attrs", {}) or {}
        if "size" in attrs:
            return int(attrs["size"])
        dtype = str(attrs.get("dtype", "fp32"))
        bits = {
            "mxfp4": 4.25,
            "int4": 5.0,
            "int8": 8.25,
            "bf16": 16.0,
            "fp16": 16.0,
            "fp32": 32.0,
        }.get(dtype, 32.0)
        return int((self._num_elements(node) * bits + 7) // 8)

    def _total_state_size(self) -> int:
        return sum(self._byte_size(node) for node in self._nodes() if node.op == "state")
