import {
  DEMO_ORG_ID,
  TEAM_AJAY_ID,
  TEAM_NIKIL_ID,
  TEAM_MARY_ID,
  TEAM_VARUN_ID,
  TEAM_AKSHITA_ID,
} from "./domain/constants.js";

const SE_PASSWORD = "se123";
const MGR_PASSWORD = "mgr123";
const LEADER_PASSWORD = "leader123";

/** Dummy accounts for development until Firebase SSO is wired. */
export const DUMMY_USERS = {
  "product.pm@freshworks.com": {
    password: "pm123",
    role: "pm",
    name: "Maya Chen",
    jobTitle: "Product Manager - CX Platform",
    teamId: null,
    orgId: DEMO_ORG_ID,
    managerEmail: "vipin.thomas@freshworks.com",
  },
  "vipin.thomas@freshworks.com": {
    password: "vipin123",
    role: "manager",
    name: "Vipin Thomas",
    jobTitle: "Senior Director - CX Customer Solutions & Strategy",
    teamId: null,
    orgId: DEMO_ORG_ID,
    managerId: null,
  },
  "antony.sagayaraj@freshworks.com": {
    password: LEADER_PASSWORD,
    role: "manager",
    name: "Antony Sagayaraj",
    jobTitle: "Senior Manager - Solution Engineering",
    teamId: null,
    orgId: DEMO_ORG_ID,
    managerEmail: "vipin.thomas@freshworks.com",
  },
  "preethi.sri@freshworks.com": {
    password: LEADER_PASSWORD,
    role: "manager",
    name: "Preethi Sri",
    jobTitle: "Senior Manager - Solution Engineering",
    teamId: null,
    orgId: DEMO_ORG_ID,
    managerEmail: "vipin.thomas@freshworks.com",
  },
  "preethi.sriram@freshworks.com": {
    password: LEADER_PASSWORD,
    role: "manager",
    name: "Preethi Sriram",
    jobTitle: "Senior Manager - Solution Engineering",
    teamId: null,
    orgId: DEMO_ORG_ID,
    managerEmail: "vipin.thomas@freshworks.com",
  },
  "ajay.raghavan@freshworks.com": {
    password: MGR_PASSWORD,
    role: "manager",
    name: "Ajay Simhan",
    jobTitle: "Manager - Solution Engineering",
    teamId: TEAM_AJAY_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "antony.sagayaraj@freshworks.com",
  },
  "nikil.ravi@freshworks.com": {
    password: MGR_PASSWORD,
    role: "manager",
    name: "Nikil Ravi",
    jobTitle: "Manager - Solution Engineering",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "antony.sagayaraj@freshworks.com",
  },
  "mary.sheeba@freshworks.com": {
    password: MGR_PASSWORD,
    role: "manager",
    name: "Mary Sheeba",
    jobTitle: "Manager - Solution Engineering",
    teamId: TEAM_MARY_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "preethi.sriram@freshworks.com",
  },
  "varun.barathy@freshworks.com": {
    password: MGR_PASSWORD,
    role: "manager",
    name: "Varun Kanna",
    jobTitle: "Manager - Solution Engineering",
    teamId: TEAM_VARUN_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "preethi.sriram@freshworks.com",
  },
  "saketh.poruri@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Saketh Poruri",
    jobTitle: "Solution Engineer",
    teamId: TEAM_AJAY_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "ajay.raghavan@freshworks.com",
  },
  "balaji.ramkumar@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Balaji R",
    jobTitle: "Lead - Solution Engineer",
    teamId: TEAM_AJAY_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "ajay.raghavan@freshworks.com",
  },
  "shaun.rozario@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Shaun Rozario",
    jobTitle: "Senior Solution Engineer",
    teamId: TEAM_AJAY_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "ajay.raghavan@freshworks.com",
  },
  "jishnu.sadanandan@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Jishnu S",
    jobTitle: "Senior Solution Engineer",
    teamId: TEAM_AJAY_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "ajay.raghavan@freshworks.com",
  },
  "snehil.nair@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Snehil Nair",
    jobTitle: "Solution Engineer",
    teamId: TEAM_AJAY_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "ajay.raghavan@freshworks.com",
  },
  "vivehanandan.agoram@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Vivehanandan Agoram",
    jobTitle: "Senior Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "mohamed.husaam@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Mohamed Husaam",
    jobTitle: "Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "sathish.kuttan@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Sathish kuttan",
    jobTitle: "Senior Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "shamron.mariyas@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Shamron Mariya S",
    jobTitle: "Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "karthik.muthiah@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Karthik Muthiah",
    jobTitle: "Lead - Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "nivedha.natarajan@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Nivedha Natarajan",
    jobTitle: "Lead - Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "aakash.poraith1@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Aakash P",
    jobTitle: "Senior Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "nitish.radha@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Nitish Radha",
    jobTitle: "Senior Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "kritika.saxena@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Kritika Saxena",
    jobTitle: "Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "khader.hussain@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Khader Sha",
    jobTitle: "Senior Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "thajudeen.shaheen@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Thajudeen Shaheen",
    jobTitle: "Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "sowrav.sunil@freshworks.com": {
    password: SE_PASSWORD,
    role: "admin",
    name: "Sowrav Sunil",
    jobTitle: "Lead - Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "swetha.suresh@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Swetha Suresh",
    jobTitle: "Senior Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "gayathri.ravikumar@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Gayathri T R",
    jobTitle: "Senior Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "pavithra.velkannan@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Pavithra Velkannan",
    jobTitle: "Senior Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "vijai.vijayakumar@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Vijai Vijayakumar",
    jobTitle: "Solution Engineer",
    teamId: TEAM_MARY_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "mary.sheeba@freshworks.com",
  },
  "cibby.kurian@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Cibby Kurian",
    jobTitle: "Solution Engineer",
    teamId: TEAM_MARY_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "mary.sheeba@freshworks.com",
  },
  "jessica.rodrigues@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Jessica Rodrigues",
    jobTitle: "Senior Solution Engineer",
    teamId: TEAM_MARY_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "mary.sheeba@freshworks.com",
  },
  "noel.fernandes@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Noel Fernandes",
    jobTitle: "Solution Engineer",
    teamId: TEAM_MARY_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "mary.sheeba@freshworks.com",
  },
  "pradeep.kumar@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Pradeep Kumar",
    jobTitle: "Senior Solution Engineer",
    teamId: TEAM_MARY_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "mary.sheeba@freshworks.com",
  },
  "ravikkumar.s@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Ravikkumar S",
    jobTitle: "Solution Engineer",
    teamId: TEAM_MARY_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "mary.sheeba@freshworks.com",
  },
  "sarwer.hussain@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Sarwer Hussain",
    jobTitle: "Solution Engineer",
    teamId: TEAM_VARUN_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "varun.barathy@freshworks.com",
  },
  "stefy.john@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Stefy John",
    jobTitle: "Solution Engineer",
    teamId: TEAM_VARUN_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "varun.barathy@freshworks.com",
  },
  "avinash.kumar@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Avinash Kumar",
    jobTitle: "Solution Engineer",
    teamId: TEAM_AKSHITA_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "preethi.sri@freshworks.com",
  },
  "calvin.joseph@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Calvin Joseph",
    jobTitle: "Senior Solution Engineer",
    teamId: TEAM_AKSHITA_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "preethi.sri@freshworks.com",
  },
  "dikshika.sharma@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Dikshika Sharma",
    jobTitle: "Solution Engineer",
    teamId: TEAM_AKSHITA_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "preethi.sri@freshworks.com",
  },
  "gautham.r@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Gautham R",
    jobTitle: "Lead - Solution Engineer",
    teamId: TEAM_AKSHITA_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "preethi.sri@freshworks.com",
  },
  "nafisa.khan@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Nafisa Khan",
    jobTitle: "Solution Engineer",
    teamId: TEAM_AKSHITA_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "preethi.sri@freshworks.com",
  },
  "mrinalini.p@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Mrinalini P",
    jobTitle: "Senior Solution Engineer",
    teamId: TEAM_AKSHITA_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "preethi.sri@freshworks.com",
  },
  "sacheeka.d@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Sacheeka D",
    jobTitle: "Solution Engineer",
    teamId: TEAM_AKSHITA_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "preethi.sri@freshworks.com",
  },
  "swetha.j@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Swetha J",
    jobTitle: "Senior Solution Engineer",
    teamId: TEAM_AKSHITA_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "preethi.sri@freshworks.com",
  },
  "se@freshworks.com": {
    password: SE_PASSWORD,
    role: "se",
    name: "Alex SE",
    jobTitle: "Solution Engineer",
    teamId: TEAM_AJAY_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "ajay.raghavan@freshworks.com",
  },
};
