import {
  DEMO_ORG_ID,
  TEAM_AJAY_ID,
  TEAM_NIKIL_ID,
  TEAM_PREETHI_SRI_ID,
  TEAM_PREETHI_SRIRAM_ID,
} from "./domain/constants.js";

/** Dummy accounts for development until Firebase SSO is wired. */
export const DUMMY_USERS = {
  "product.pm@freshworks.com": {
    password: "pm123",
    role: "pm",
    name: "Maya Chen",
    jobTitle: "Product Manager — CX Platform",
    teamId: null,
    orgId: DEMO_ORG_ID,
    managerEmail: "vipin.thomas@freshworks.com",
  },
  "vipin.thomas@freshworks.com": {
    password: "vipin123",
    role: "manager",
    name: "Vipin Thomas",
    jobTitle: "Senior Director - CX Customer Solutions & Strategy",
    teamId: null,
    orgId: DEMO_ORG_ID,
    managerId: null,
  },
  "antony.sagayaraj@freshworks.com": {
    password: "leader123",
    role: "manager",
    name: "Antony Sagayaraj",
    jobTitle: "Senior Manager - Solution Engineering",
    teamId: null,
    orgId: DEMO_ORG_ID,
    managerEmail: "vipin.thomas@freshworks.com",
  },
  "preethi.sri@freshworks.com": {
    password: "leader123",
    role: "manager",
    name: "Preethi Sri",
    jobTitle: "Senior Manager - Solution Engineering",
    teamId: null,
    orgId: DEMO_ORG_ID,
    managerEmail: "vipin.thomas@freshworks.com",
  },
  "preethi.sriram@freshworks.com": {
    password: "leader123",
    role: "manager",
    name: "Preethi Sriram",
    jobTitle: "Senior Manager - Solution Engineering",
    teamId: null,
    orgId: DEMO_ORG_ID,
    managerEmail: "vipin.thomas@freshworks.com",
  },
  "ajay.raghavan@freshworks.com": {
    password: "mgr123",
    role: "manager",
    name: "Ajay Simhan",
    jobTitle: "Manager - Solution Engineering",
    teamId: TEAM_AJAY_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "antony.sagayaraj@freshworks.com",
  },
  "nikil.ravi@freshworks.com": {
    password: "mgr123",
    role: "manager",
    name: "Nikil Ravi",
    jobTitle: "Manager - Solution Engineering",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "antony.sagayaraj@freshworks.com",
  },
  "manager.preethi.sri@freshworks.com": {
    password: "mgr123",
    role: "manager",
    name: "Anita Desai",
    jobTitle: "Manager - Solution Engineering",
    teamId: TEAM_PREETHI_SRI_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "preethi.sri@freshworks.com",
  },
  "manager.preethi.sriram@freshworks.com": {
    password: "mgr123",
    role: "manager",
    name: "Karthik Menon",
    jobTitle: "Manager - Solution Engineering",
    teamId: TEAM_PREETHI_SRIRAM_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "preethi.sriram@freshworks.com",
  },
  // International - NB — Solution Engineers
  "saketh.poruri@freshworks.com": {
    password: "se123",
    role: "se",
    name: "Saketh Poruri",
    jobTitle: "Solution Engineer",
    teamId: TEAM_AJAY_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "ajay.raghavan@freshworks.com",
  },
  "balaji.ramkumar@freshworks.com": {
    password: "se123",
    role: "se",
    name: "Balaji R",
    jobTitle: "Lead - Solution Engineer",
    teamId: TEAM_AJAY_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "ajay.raghavan@freshworks.com",
  },
  "shaun.rozario@freshworks.com": {
    password: "se123",
    role: "se",
    name: "Shaun Rozario",
    jobTitle: "Senior Solution Engineer",
    teamId: TEAM_AJAY_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "ajay.raghavan@freshworks.com",
  },
  "jishnu.sadanandan@freshworks.com": {
    password: "se123",
    role: "se",
    name: "Jishnu S",
    jobTitle: "Senior Solution Engineer",
    teamId: TEAM_AJAY_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "ajay.raghavan@freshworks.com",
  },
  // North America - NB — Solution Engineers
  "vivehanandan.agoram@freshworks.com": {
    password: "se123",
    role: "se",
    name: "Vivehanandan Agoram",
    jobTitle: "Senior Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "mohamed.husaam@freshworks.com": {
    password: "se123",
    role: "se",
    name: "Mohamed Husaam",
    jobTitle: "Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "sathish.kuttan@freshworks.com": {
    password: "se123",
    role: "se",
    name: "Sathish kuttan",
    jobTitle: "Senior Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "shamron.mariyas@freshworks.com": {
    password: "se123",
    role: "se",
    name: "Shamron Mariya S",
    jobTitle: "Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "karthik.muthiah@freshworks.com": {
    password: "se123",
    role: "se",
    name: "Karthik Muthiah",
    jobTitle: "Lead - Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "nivedha.natarajan@freshworks.com": {
    password: "se123",
    role: "se",
    name: "Nivedha Natarajan",
    jobTitle: "Lead - Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "aakash.poraith1@freshworks.com": {
    password: "se123",
    role: "se",
    name: "Aakash P",
    jobTitle: "Senior Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "nitish.radha@freshworks.com": {
    password: "se123",
    role: "se",
    name: "Nitish Radha",
    jobTitle: "Senior Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "kritika.saxena@freshworks.com": {
    password: "se123",
    role: "se",
    name: "Kritika Saxena",
    jobTitle: "Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "khader.hussain@freshworks.com": {
    password: "se123",
    role: "se",
    name: "Khader Sha",
    jobTitle: "Senior Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "thajudeen.shaheen@freshworks.com": {
    password: "se123",
    role: "se",
    name: "Thajudeen Shaheen",
    jobTitle: "Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "sowrav.sunil@freshworks.com": {
    password: "se123",
    role: "admin",
    name: "Sowrav Sunil",
    jobTitle: "Lead - Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "swetha.suresh@freshworks.com": {
    password: "se123",
    role: "se",
    name: "Swetha Suresh",
    jobTitle: "Senior Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "gayathri.ravikumar@freshworks.com": {
    password: "se123",
    role: "se",
    name: "Gayathri T R",
    jobTitle: "Senior Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "pavithra.velkannan@freshworks.com": {
    password: "se123",
    role: "se",
    name: "Pavithra Velkannan",
    jobTitle: "Senior Solution Engineer",
    teamId: TEAM_NIKIL_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "nikil.ravi@freshworks.com",
  },
  "se.preethi.sri.1@freshworks.com": {
    password: "se123",
    role: "se",
    name: "Meera Iyer",
    jobTitle: "Solution Engineer",
    teamId: TEAM_PREETHI_SRI_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "manager.preethi.sri@freshworks.com",
  },
  "se.preethi.sri.2@freshworks.com": {
    password: "se123",
    role: "se",
    name: "Vikram Singh",
    jobTitle: "Solution Engineer",
    teamId: TEAM_PREETHI_SRI_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "manager.preethi.sri@freshworks.com",
  },
  "se.preethi.sriram.1@freshworks.com": {
    password: "se123",
    role: "se",
    name: "Divya Nair",
    jobTitle: "Solution Engineer",
    teamId: TEAM_PREETHI_SRIRAM_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "manager.preethi.sriram@freshworks.com",
  },
  "se.preethi.sriram.2@freshworks.com": {
    password: "se123",
    role: "se",
    name: "Rohan Das",
    jobTitle: "Solution Engineer",
    teamId: TEAM_PREETHI_SRIRAM_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "manager.preethi.sriram@freshworks.com",
  },
  // Legacy alias — assigned to International - NB until real IC roster is added.
  "se@freshworks.com": {
    password: "se123",
    role: "se",
    name: "Alex SE",
    jobTitle: "Solution Engineer",
    teamId: TEAM_AJAY_ID,
    orgId: DEMO_ORG_ID,
    managerEmail: "ajay.raghavan@freshworks.com",
  },
};
